# Generated by Django 2.0.4 on 2018-04-06 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('funcionario', 'Funcionário')], default=1, max_length=175, verbose_name='Cargo'),
            preserve_default=False,
        ),
    ]
