# Generated by Django 2.0.4 on 2018-05-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20180406_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='addrees',
        ),
        migrations.AddField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
