GENERATE_LATEX = False
EXTRACT_ALL = True
RECURSIVE = True
GENERATE_TREEVIEW = True
DISABLE_INDEX = True

PROJECT_NAME = "MES-Cloud"
EXCLUDE_PATTERNS = "*/migrations/*"
FILE_PATTERNS = "*.py"
OUTPUT_DIRECTORY = "docs/code/"
