version: '3'

services:
  postgres:
    image: "postgres:11-alpine"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  mongo:
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  web:
    build: .
    command: "./docker-entrypoint.sh"
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/mes-cloud
    depends_on:
      - postgres
      - mongo

volumes:
  postgres_data:
  mongo_data:
