# Generated by Django 2.0.4 on 2018-04-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceProduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('ice_type', models.CharField(choices=[('tubo', 'Tubo'), ('escama', 'Escama'), ('barra', 'Barra')], max_length=75, verbose_name='Tipo')),
                ('topic', models.CharField(max_length=175, verbose_name='Tópico MQTT')),
                ('weight', models.CharField(max_length=75, verbose_name='Peso')),
                ('date', models.DateField(verbose_name='Data')),
                ('hour', models.TimeField(verbose_name='Horário')),
            ],
            options={
                'verbose_name': 'Produção de Gelo',
                'verbose_name_plural': 'Produção de Gelo',
            },
        ),
    ]
